// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMBgl746XLyIu-6m5X__OxhynoawT6Tw',
    appId: '1:326995308043:web:8efa1126f13e194c3c210e',
    messagingSenderId: '326995308043',
    projectId: 'shark-tank-9357a',
    authDomain: 'shark-tank-9357a.firebaseapp.com',
    storageBucket: 'shark-tank-9357a.appspot.com',
    measurementId: 'G-MP1VBC54S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACoeu78rl2Fd4GalWe8dWQAO5Oe2XZSEs',
    appId: '1:326995308043:android:592641fb6fbcfb9b3c210e',
    messagingSenderId: '326995308043',
    projectId: 'shark-tank-9357a',
    storageBucket: 'shark-tank-9357a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsO8OGE3joEeu7j6LSoZ8gXplPVp8lm2U',
    appId: '1:326995308043:ios:405b8126b5e263663c210e',
    messagingSenderId: '326995308043',
    projectId: 'shark-tank-9357a',
    storageBucket: 'shark-tank-9357a.appspot.com',
    iosClientId: '326995308043-ge2sjqcp4sqcco15uiqps4b7ckdllor3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharktank',
  );
}
